/**
 * Script to fix specific sticky words and remaining artifacts in corpus.ts
 */

const fs = require('fs');
const path = require('path');

const corpusPath = path.join(__dirname, 'src/lib/data/corpus.ts');
let content = fs.readFileSync(corpusPath, 'utf8');

const specificFixes = [
    // Long sticky words from scan
    ['muốngianhậphoặc', 'muốn gia nhập hoặc'],
    ['mừnghátAlleluia', 'mừng hát Alleluia'],
    ['tranghoànghẳnhoi', 'trang hoàng hẳn hoi'],

    // CamelCase / Capitalization sticky words
    ['BácÁi', 'Bác Ái'],
    ['bácÁi', 'bác Ái'],
    ['đứcÁi', 'đức Ái'],
    ['PhúcÂm', 'Phúc Âm'],
    ['PhúcÂ', 'Phúc Â'],
    ['TânƯớc', 'Tân Ước'],
    ['TânƯ', 'Tân Ư'],
    ['CựuƯớc', 'Cựu Ước'],
    ['CựuƯ', 'Cựu Ư'],
    ['Ơngọi', 'Ơn gọi'],
    ['ơngọi', 'ơn gọi'],
    ['máyIBM', 'máy IBM'],
    ['bênAi', 'bên Ai'],
    ['đếnAi', 'đến Ai'],
    ['ThánhThể', 'Thánh Thể'],
    ['GiáoHội', 'Giáo Hội'],
    ['GiáoDân', 'Giáo Dân'],
    ['CôngĐồng', 'Công Đồng'],

    // Lowercase sticky words
    ['thựchiện', 'thực hiện'],
    ['hânhoan', 'hân hoan'],
    ['hânhoanhát', 'hân hoan hát'],
    ['vinhdanh', 'vinh danh'],
    ['ômấp', 'ôm ấp'],
    ['tânhôn', 'tân hôn'],
    ['tânhônở', 'tân hôn ở'],
    ['biếtrõ', 'biết rõ'],
    ['tậnHiến', 'tận Hiến'], // Mixed case
    ['tậnhiến', 'tận hiến'],
    ['cáchội', 'các hội'], // "các hội viên"
    ['cảnhà', 'cả nhà'],
    ['cầnthiết', 'cần thiết'],
    ['tấtcảnhững', 'tất cả những'],
    ['tấtcả', 'tất cả'],
    ['cảnhững', 'cả những'],
    ['ranhư', 'ra như'],
    ['Chanhân', 'Cha nhân'],
    ['bácái', 'bác ái'], // re-apply just in case

    // Common joined words that might occur
    ['lờichúa', 'lời chúa'],
    ['LờiChúa', 'Lời Chúa'],
    ['ThánhKinh', 'Thánh Kinh'],
    ['nướcChúa', 'nước Chúa'],
    ['dânChúa', 'dân Chúa'],
    ['conngười', 'con người'],
    ['mọingười', 'mọi người'],
    ['thếgiới', 'thế giới'],
    ['hoabình', 'hòa bình'],
    ['tựdo', 'tự do'],
    ['cônglý', 'công lý'],
    ['sựthật', 'sự thật'],
    ['chânlý', 'chân lý'],
    ['việcngĩa', 'việc nghĩa'], // typo? việc nghĩa
    ['việcnghĩa', 'việc nghĩa'],

    // Fix potential bad joins from previous regex
    ['vớicác', 'với các'],
    ['củaác', 'của các'], // if "c ủa c ác" -> "củaác"? Check context
    ['vềc', 'về c'], // likely "về các" or "về cõi"
    ['làc', 'là c'],
    ['củac', 'của c'],
    ['choC', 'cho C'],
    ['choTi', 'cho Ti'],
    ['hoanhãm', 'hoan hãm'],
    ['hiệný', 'hiện ý'],
    ['nguyệný', 'nguyện ý'],
    ['nguyệnv', 'nguyện v'],

    // Manual fixes from scan-stickies.js (High frequency)
    ['nhữnghoàn', 'những hoàn'],
    ['truyềngiáo', 'truyền giáo'],
    ['khônghiểu', 'không hiểu'],
    ['giữanhững', 'giữa những'],
    ['thônghiệp', 'thông hiệp'],
    ['nhữnghành', 'những hành'],
    ['khủnghoảng', 'khủng hoảng'],
    ['khônghành', 'không hành'],
    ['nhữnghình', 'những hình'],
    ['Giữanhững', 'Giữa những'],
    ['trườnghợp', 'trường hợp'],
    ['chẳnghiểu', 'chẳng hiểu'],
    ['Cácônghãy', 'Các ông hãy'],
    ['trườnghoạt', 'trường hoạt'],
    ['trườnghọc', 'trường học'],
    ['nêngiốnghình', 'nên giống hình'],
    ['thườnghay', 'thường hay'],
    ['nhữnghiện', 'những hiện'],
    ['luôngìngi', 'luôn gìn giữ'],
    ['tronghành', 'trong hành'],
    ['Khủnghoảng', 'Khủng hoảng'],
    ['Chúanhững', 'Chúa những'],
    ['thônghiệpấy', 'thông hiệp ấy'],
    ['tronghoàn', 'trong hoàn'],
    ['thônghuynh', 'thông huynh'],
    ['truyềnhình', 'truyền hình'],
    ['chuyệnhoang', 'chuyện hoang'],
    ['nhữnghoạt', 'những hoạt'],
    ['nganghàng', 'ngang hàng'],
    ['thônghiểu', 'thông hiểu'],
    ['quyềnhành', 'quyền hành'],
    ['nhiênhưởng', 'nhiên hưởng'],
    ['giốnghình', 'giống hình'],
    ['nhấthuynh', 'nhất huynh'],
    ['conhãyyêu', 'con hãy yêu'],
    ['khônghoán', 'không hoán'],
    ['khônghẹphòi', 'không hẹp hòi'],
    ['ngừnghọchỏi', 'ngừng học hỏi'],
    ['trạnghuống', 'trạng huống'],
    ['nghiệphay', 'nghiệp hay'],
    ['quyếthành', 'quyết hành'],
    ['quyếthạnh', 'quyết hạnh'],
    ['thắphương', 'thắp hương'],
    ['quyềngiáo', 'quyền giáo'],
    ['thươnghơnhết', 'thương hơn hết'],
    ['việcănuống', 'việc ăn uống'],
    ['chuyệngiữa', 'chuyện giữa'],
    ['nguyệngiống', 'nguyện giống'],
    ['bănghuyết', 'băng huyết'],
    ['nguyệngiúp', 'nguyện giúp'],
    ['nhưnghạng', 'nhưng hạng'],
    ['lònghiềnho', 'lòng hiền hòa'],
    ['khoangiận', 'khoan giận'],
    ['anghùnghồn', 'đang hùng hồn'],
    ['gianghétanh', 'gian ghét anh'],
    ['chứchoànhảo', 'chức hoàn hảo'],
    ['tronghàng', 'trong hàng'],
    ['dângiúpích', 'dân giúp ích'],
    ['nghiệphơn', 'nghiệp hơn'],
    ['thiênhình', 'thiên hình'],
    ['khônghoạt', 'không hoạt'],
    ['nhữnghạng', 'những hạng'],
    ['thônghưởng', 'thông hưởng'],
    ['Thônghiệp', 'Thông hiệp'],
    ['luônhướng', 'luôn hướng'],
    ['cácônghơn', 'các ông hơn'],
    ['Thầnhướng', 'Thần hướng'],
    ['chunghưởng', 'chung hưởng'],
    ['bầnghengh', 'bần ghê người'],
    ['bầnuấthận', 'bần uất hận'],
    ['khuyênanh', 'khuyên anh'],
    ['khônghiện', 'không hiện'],
    ['trắnghạng', 'trắng hạng'], // trắng tay? trang hạng?
    ['kếthợphơn', 'kết hợp hơn'],
    ['nhữnghiệphội', 'những hiệp hội'],
    ['tiệchếtrượu', 'tiệc hết rượu'],
    ['tiếngầnhơn', 'tiến gần hơn'],
    ['chồnghãyyêu', 'chồng hãy yêu'],
    ['xuyêngiúp', 'xuyên giúp'],
    ['tronghoan', 'trong hoan'],
    ['kếthợpyếu', 'kết hợp yếu'],
    ['conhơnhồi', 'con hơn hồi'],
    ['Kitônghèo', 'Kitô nghèo'],
    ['khănhơnhân', 'khăn hơn hân'],
    ['sốnghiềnho', 'sống hiền hòa'],
    ['thươnghuynh', 'thương huynh'],
    ['nhưnghướng', 'nhưng hướng'],
    ['Quyềngiáo', 'Quyền giáo'],
    ['thuậthoạt', 'thuật hoạt'],
    ['Cànghọchỏi', 'Càng học hỏi'],
    ['Trườnghợp', 'Trường hợp'],
    ['cùnghưởng', 'cùng hưởng'],
    ['việchuynh', 'việc huynh'],
    ['bằnghoànhảo', 'bằng hoàn hảo'],
    ['khuyênhiến', 'khuyên hiến'],
    ['nguyệnhiến', 'nguyện hiến'],
    ['nghoànhảo', 'ng hoàn hảo'],
    ['khuấthình', 'khuất hình'],
    ['quyếthoàn', 'quyết hoàn'],
    ['nhữnghàng', 'những hàng'],
    ['thiệnhoàn', 'thiện hoàn'],
    ['tiếnhơnhôm', 'tiến hơn hôm'],
    ['tắnhồnghào', 'tắn hồng hào'],
    ['chuyệngiật', 'chuyện giật'],
    ['phấthương', 'phất hương'],
    ['chỉđượchoàn', 'chỉ được hoàn'],
    ['quyếtrằng', 'quyết rằng'],
    ['hưởnghạnh', 'hưởng hạnh'],
    ['xáchấphối', 'xác hấp hối'],
    ['nênhoànhảo', 'nên hoàn hảo'],
    ['Sốnghuynh', 'Sống huynh'],
    ['sốnghuynh', 'sống huynh'],
    ['thốtranhững', 'thốt ra những'],
    ['chúnghình', 'chúng hình'],
    ['thănghoanhững', 'thăng hoa những'],
    ['lêngiường', 'lên giường'],
    ['khônghoàn', 'không hoàn'],
    ['congiúpai', 'con giúp ai'],
    ['thanhânhình', 'thân hình'],
    ['vônghĩanhất', 'vô nghĩa nhất'],
    ['chuyệnhạt', 'chuyện hạt'],
    ['nhiệthuyết', 'nhiệt huyết'],
    ['khônghiếu', 'không hiếu'],
    ['nhưnghãyân', 'nhưng hãy ân'],
    ['quyếthằng', 'quyết hằng'],
    ['mộtíthiện', 'một ít thiện'],
    ['Trườnghọc', 'Trường học'],
    ['Trướchoài', 'Trước hoài'],
    ['hươnghạnh', 'hương hạnh'],
    ['toànhướng', 'toàn hướng'],
    ['thuậnhiến', 'thuận hiến'],
    ['thươnghải', 'thương hải'],
    ['khủnghoảnghy', 'khủng hoảng hy'],
    ['chúnghiệnhữu', 'chúng hiện hữu'],
    ['tronghiện', 'trong hiện'],
    ['Truyềnhình', 'Truyền hình'],
    ['dânghiếnấy', 'dâng hiến ấy'],

    // Round 3 Scan
    ['Maisengiang', 'Maisen giang'],
    ['Thiênhạ', 'Thiên hạ'],
    ['hạnhánở', 'hạn hán ở'],
    ['sóng thầnở', 'sóng thần ở'],
    ['thầnở', 'thần ở'],
    ['NamM', 'Nam M'],
    ['nhưnghãy', 'nhưng hãy'],
    ['mấya', 'mấy ai'],
];

let count = 0;
for (const [pattern, replacement] of specificFixes) {
    if (content.includes(pattern)) {
        content = content.split(pattern).join(replacement);
        count++;
    }
}

console.log(`Applied ${count} types of specific sticky word fixes.`);

fs.writeFileSync(corpusPath, content, 'utf8');
