/**
 * Script to fix specific sticky words and remaining artifacts in corpus.ts
 */

const fs = require('fs');
const path = require('path');

const corpusPath = path.join(__dirname, 'src/lib/data/corpus.ts');
let content = fs.readFileSync(corpusPath, 'utf8');

const specificFixes = [
    // Long sticky words from scan
    ['muốngianhậphoặc', 'muốn gia nhập hoặc'],
    ['mừnghátAlleluia', 'mừng hát Alleluia'],
    ['tranghoànghẳnhoi', 'trang hoàng hẳn hoi'],

    // CamelCase / Capitalization sticky words
    ['BácÁi', 'Bác Ái'],
    ['bácÁi', 'bác Ái'],
    ['đứcÁi', 'đức Ái'],
    ['PhúcÂm', 'Phúc Âm'],
    ['PhúcÂ', 'Phúc Â'],
    ['TânƯớc', 'Tân Ước'],
    ['TânƯ', 'Tân Ư'],
    ['CựuƯớc', 'Cựu Ước'],
    ['CựuƯ', 'Cựu Ư'],
    ['Ơngọi', 'Ơn gọi'],
    ['ơngọi', 'ơn gọi'],
    ['máyIBM', 'máy IBM'],
    ['bênAi', 'bên Ai'],
    ['đếnAi', 'đến Ai'],
    ['ThánhThể', 'Thánh Thể'],
    ['GiáoHội', 'Giáo Hội'],
    ['GiáoDân', 'Giáo Dân'],
    ['CôngĐồng', 'Công Đồng'],

    // Lowercase sticky words
    ['thựchiện', 'thực hiện'],
    ['hânhoan', 'hân hoan'],
    ['hânhoanhát', 'hân hoan hát'],
    ['vinhdanh', 'vinh danh'],
    ['ômấp', 'ôm ấp'],
    ['tânhôn', 'tân hôn'],
    ['tânhônở', 'tân hôn ở'],
    ['biếtrõ', 'biết rõ'],
    ['tậnHiến', 'tận Hiến'], // Mixed case
    ['tậnhiến', 'tận hiến'],
    ['cáchội', 'các hội'], // "các hội viên"
    ['cảnhà', 'cả nhà'],
    ['cầnthiết', 'cần thiết'],
    ['tấtcảnhững', 'tất cả những'],
    ['tấtcả', 'tất cả'],
    ['cảnhững', 'cả những'],
    ['ranhư', 'ra như'],
    ['Chanhân', 'Cha nhân'],
    ['bácái', 'bác ái'], // re-apply just in case

    // Common joined words that might occur
    ['lờichúa', 'lời chúa'],
    ['LờiChúa', 'Lời Chúa'],
    ['ThánhKinh', 'Thánh Kinh'],
    ['nướcChúa', 'nước Chúa'],
    ['dânChúa', 'dân Chúa'],
    ['conngười', 'con người'],
    ['mọingười', 'mọi người'],
    ['thếgiới', 'thế giới'],
    ['hoabình', 'hòa bình'],
    ['tựdo', 'tự do'],
    ['cônglý', 'công lý'],
    ['sựthật', 'sự thật'],
    ['chânlý', 'chân lý'],
    ['việcngĩa', 'việc nghĩa'], // typo? việc nghĩa
    ['việcnghĩa', 'việc nghĩa'],

    // Fix potential bad joins from previous regex
    ['vớicác', 'với các'],
    ['củaác', 'của các'], // if "c ủa c ác" -> "củaác"? Check context
    ['vềc', 'về c'], // likely "về các" or "về cõi"
    ['làc', 'là c'],
    ['củac', 'của c'],
    ['choC', 'cho C'],
    ['choTi', 'cho Ti'],
    ['hoanhãm', 'hoan hãm'],
    ['hiệný', 'hiện ý'],
    ['nguyệný', 'nguyện ý'],
    ['nguyệnv', 'nguyện v'],

    // Manual fixes from scan-stickies.js (High frequency)
    ['nhữnghoàn', 'những hoàn'],
    ['truyềngiáo', 'truyền giáo'],
    ['khônghiểu', 'không hiểu'],
    ['giữanhững', 'giữa những'],
    ['thônghiệp', 'thông hiệp'],
    ['nhữnghành', 'những hành'],
    ['khủnghoảng', 'khủng hoảng'],
    ['khônghành', 'không hành'],
    ['nhữnghình', 'những hình'],
    ['Giữanhững', 'Giữa những'],
    ['trườnghợp', 'trường hợp'],
    ['chẳnghiểu', 'chẳng hiểu'],
    ['Cácônghãy', 'Các ông hãy'],
    ['trườnghoạt', 'trường hoạt'],
    ['trườnghọc', 'trường học'],
    ['nêngiốnghình', 'nên giống hình'],
    ['thườnghay', 'thường hay'],
    ['nhữnghiện', 'những hiện'],
    ['luôngìngi', 'luôn gìn giữ'],
    ['tronghành', 'trong hành'],
    ['Khủnghoảng', 'Khủng hoảng'],
    ['Chúanhững', 'Chúa những'],
    ['thônghiệpấy', 'thông hiệp ấy'],
    ['tronghoàn', 'trong hoàn'],
    ['thônghuynh', 'thông huynh'],
    ['truyềnhình', 'truyền hình'],
    ['chuyệnhoang', 'chuyện hoang'],
    ['nhữnghoạt', 'những hoạt'],
    ['nganghàng', 'ngang hàng'],
    ['thônghiểu', 'thông hiểu'],
    ['quyềnhành', 'quyền hành'],
    ['nhiênhưởng', 'nhiên hưởng'],
    ['giốnghình', 'giống hình'],
    ['nhấthuynh', 'nhất huynh'],
    ['conhãyyêu', 'con hãy yêu'],
    ['khônghoán', 'không hoán'],
    ['khônghẹphòi', 'không hẹp hòi'],
    ['ngừnghọchỏi', 'ngừng học hỏi'],
    ['trạnghuống', 'trạng huống'],
    ['nghiệphay', 'nghiệp hay'],
    ['quyếthành', 'quyết hành'],
    ['quyếthạnh', 'quyết hạnh'],
    ['thắphương', 'thắp hương'],
    ['quyềngiáo', 'quyền giáo'],
    ['thươnghơnhết', 'thương hơn hết'],
    ['việcănuống', 'việc ăn uống'],
    ['chuyệngiữa', 'chuyện giữa'],
    ['nguyệngiống', 'nguyện giống'],
    ['bănghuyết', 'băng huyết'],
    ['nguyệngiúp', 'nguyện giúp'],
    ['nhưnghạng', 'nhưng hạng'],
    ['lònghiềnho', 'lòng hiền hòa'],
    ['khoangiận', 'khoan giận'],
    ['anghùnghồn', 'đang hùng hồn'],
    ['gianghétanh', 'gian ghét anh'],
    ['chứchoànhảo', 'chức hoàn hảo'],
    ['tronghàng', 'trong hàng'],
    ['dângiúpích', 'dân giúp ích'],
    ['nghiệphơn', 'nghiệp hơn'],
    ['thiênhình', 'thiên hình'],
    ['khônghoạt', 'không hoạt'],
    ['nhữnghạng', 'những hạng'],
    ['thônghưởng', 'thông hưởng'],
    ['Thônghiệp', 'Thông hiệp'],
    ['luônhướng', 'luôn hướng'],
    ['cácônghơn', 'các ông hơn'],
    ['Thầnhướng', 'Thần hướng'],
    ['chunghưởng', 'chung hưởng'],
    ['bầnghengh', 'bần ghê người'],
    ['bầnuấthận', 'bần uất hận'],
    ['khuyênanh', 'khuyên anh'],
    ['khônghiện', 'không hiện'],
    ['trắnghạng', 'trắng hạng'], // trắng tay? trang hạng?
    ['kếthợphơn', 'kết hợp hơn'],
    ['nhữnghiệphội', 'những hiệp hội'],
    ['tiệchếtrượu', 'tiệc hết rượu'],
    ['tiếngầnhơn', 'tiến gần hơn'],
    ['chồnghãyyêu', 'chồng hãy yêu'],
    ['xuyêngiúp', 'xuyên giúp'],
    ['tronghoan', 'trong hoan'],
    ['kếthợpyếu', 'kết hợp yếu'],
    ['conhơnhồi', 'con hơn hồi'],
    ['Kitônghèo', 'Kitô nghèo'],
    ['khănhơnhân', 'khăn hơn hân'],
    ['sốnghiềnho', 'sống hiền hòa'],
    ['thươnghuynh', 'thương huynh'],
    ['nhưnghướng', 'nhưng hướng'],
    ['Quyềngiáo', 'Quyền giáo'],
    ['thuậthoạt', 'thuật hoạt'],
    ['Cànghọchỏi', 'Càng học hỏi'],
    ['Trườnghợp', 'Trường hợp'],
    ['cùnghưởng', 'cùng hưởng'],
    ['việchuynh', 'việc huynh'],
    ['bằnghoànhảo', 'bằng hoàn hảo'],
    ['khuyênhiến', 'khuyên hiến'],
    ['nguyệnhiến', 'nguyện hiến'],
    ['nghoànhảo', 'ng hoàn hảo'],
    ['khuấthình', 'khuất hình'],
    ['quyếthoàn', 'quyết hoàn'],
    ['nhữnghàng', 'những hàng'],
    ['thiệnhoàn', 'thiện hoàn'],
    ['tiếnhơnhôm', 'tiến hơn hôm'],
    ['tắnhồnghào', 'tắn hồng hào'],
    ['chuyệngiật', 'chuyện giật'],
    ['phấthương', 'phất hương'],
    ['chỉđượchoàn', 'chỉ được hoàn'],
    ['quyếtrằng', 'quyết rằng'],
    ['hưởnghạnh', 'hưởng hạnh'],
    ['xáchấphối', 'xác hấp hối'],
    ['nênhoànhảo', 'nên hoàn hảo'],
    ['Sốnghuynh', 'Sống huynh'],
    ['sốnghuynh', 'sống huynh'],
    ['thốtranhững', 'thốt ra những'],
    ['chúnghình', 'chúng hình'],
    ['thănghoanhững', 'thăng hoa những'],
    ['lêngiường', 'lên giường'],
    ['khônghoàn', 'không hoàn'],
    ['congiúpai', 'con giúp ai'],
    ['thanhânhình', 'thân hình'],
    ['vônghĩanhất', 'vô nghĩa nhất'],
    ['chuyệnhạt', 'chuyện hạt'],
    ['nhiệthuyết', 'nhiệt huyết'],
    ['khônghiếu', 'không hiếu'],
    ['nhưnghãyân', 'nhưng hãy ân'],
    ['quyếthằng', 'quyết hằng'],
    ['mộtíthiện', 'một ít thiện'],
    ['Trườnghọc', 'Trường học'],
    ['Trướchoài', 'Trước hoài'],
    ['hươnghạnh', 'hương hạnh'],
    ['toànhướng', 'toàn hướng'],
    ['thuậnhiến', 'thuận hiến'],
    ['thươnghải', 'thương hải'],
    ['khủnghoảnghy', 'khủng hoảng hy'],
    ['chúnghiệnhữu', 'chúng hiện hữu'],
    ['tronghiện', 'trong hiện'],
    ['Truyềnhình', 'Truyền hình'],
    ['dânghiếnấy', 'dâng hiến ấy'],

    // Round 3 Scan
    ['Maisengiang', 'Maisen giang'],
    ['Thiênhạ', 'Thiên hạ'],
    ['hạnhánở', 'hạn hán ở'],
    ['sóng thầnở', 'sóng thần ở'],
    ['thầnở', 'thần ở'],
    ['NamM', 'Nam M'],
    ['nhưnghãy', 'nhưng hãy'],
    // Manual fixes from scan-polysyllabic.js
    ['Phúcâm', 'Phúc Âm'],
    ['trầngian', 'trần gian'],
    ['Conhãy', 'Con hãy'],
    ['conhãy', 'con hãy'],
    ['tínhữu', 'tín hữu'],
    ['cácông', 'các ông'],
    ['đứcái', 'đức ái'],
    ['biếtrằng', 'biết rằng'],
    ['thiênhạ', 'thiên hạ'],
    ['Bácái', 'Bác ái'],
    ['kếthiệp', 'kết hiệp'],
    ['trướchết', 'trước hết'],
    ['thanhân', 'tha nhân'],
    ['kếthợp', 'kết hợp'],
    ['thựchành', 'thực hành'],
    ['tôngiáo', 'tôn giáo'],
    ['thậtanh', 'thật anh'],
    ['củanhân', 'của nhân'],
    ['đườnghy', 'đường hy'],
    ['quanhệ', 'quan hệ'],
    ['ânhuệ', 'ân huệ'],
    ['đượchưởng', 'được hưởng'],
    ['hoànhảo', 'hoàn hảo'],
    ['quanhững', 'qua những'],
    ['lúcấy', 'lúc ấy'],
    ['nêngiống', 'nên giống'],
    ['củanhững', 'của những'],
    ['dânghiến', 'dâng hiến'],
    ['việchọ', 'việc họ'],
    ['Chúanhư', 'Chúa như'],
    ['Cònanh', 'Còn anh'],
    ['cámơn', 'cám ơn'],
    ['cácanh', 'các anh'],
    ['thiếthơn', 'thiết hơn'],
    ['mộtý', 'một ý'],
    ['mếnyêu', 'mến yêu'],
    ['conở', 'con ở'],
    ['phảnứng', 'phản ứng'],
    ['bạnhữu', 'bạn hữu'],
    ['đẹphơn', 'đẹp hơn'],
    ['niềman', 'niềm an'],
    ['trọnghơn', 'trọng hơn'],
    ['cũnghãy', 'cũng hãy'],
    ['liênhệ', 'liên hệ'],
    ['phúthiện', 'phút hiện'],
    ['khônghy', 'không hy'],
    ['cònhơn', 'còn hơn'],
    ['cònai', 'còn ai'],
    ['khấngiữ', 'khấn giữ'],
    ['nhânhậu', 'nhân hậu'],
    ['nếtở', 'nết ở'],
    ['biếtơn', 'biết ơn'],
    ['Phầnanh', 'Phần anh'],
    ['dâmô', 'dâm ô'],
    ['ănuống', 'ăn uống'],
    ['Conhỏi', 'Con hỏi'],
    ['Trướchết', 'Trước hết'],
    ['congiữ', 'con giữ'],
    ['lớnhơn', 'lớn hơn'],
    ['hănghái', 'hăng hái'],
    ['tuângiữ', 'tuân giữ'],
    ['khônghề', 'không hề'],
    ['đượcan', 'được an'],
    ['tuyệthảo', 'tuyệt hảo'],
    ['vĩđại', 'vĩ đại'],
    ['đượcyêu', 'được yêu'],
    ['xuấthiện', 'xuất hiện'],
    ['mộtai', 'một ai'],
    ['vănhoá', 'văn hoá'],
    ['đượchạnh', 'được hạnh'],
    ['kếthôn', 'kết hôn'],
    ['cònở', 'còn ở'],
    ['giảnhư', 'giả như'],
    ['chọnanh', 'chọn anh'],
    ['đượchướng', 'được hướng'],
    ['họchỏi', 'học hỏi'],
    ['hồnanh', 'hồn anh'],
    ['hiệnhữu', 'hiện hữu'],
    ['ănở', 'ăn ở'],
    ['việcanh', 'việc anh'],
    ['đồnghoá', 'đồng hoá'],
    ['mộtânhuệ', 'một ân huệ'],
    ['bênhữu', 'bên hữu'],
    ['nhưnghọ', 'nhưng họ'],
    ['thầnhọc', 'thần học'],
    ['Cácanh', 'Các anh'],
    ['Chúanhờ', 'Chúa nhờ'],
    ['giúphọ', 'giúp họ'],
    ['gìngiữ', 'gìn giữ'],
    ['củanhau', 'của nhau'],
    ['cáchoạt', 'các hoạt'],
    ['nhữnghậu', 'những hậu'],
    ['Mađalêna', 'Mađalêna'], // Name, ignore
    ['Nagiarét', 'Nagiarét'],
    ['Phanxicô', 'Phanxicô'],
    ['Giêrusalem', 'Giêrusalem'],
    ['Calvariô', 'Calvariô'],
    ['Giuđa', 'Giuđa'],
    ['Rôma', 'Rôma'],
    // Round 2 Manual fixes from scan-polysyllabic.js
    ['mộtân', 'một ân'],
    ['đượcơn', 'được ơn'],
    ['Lúcấy', 'Lúc ấy'],
    ['conhi', 'con hy'], // Guessing hy usually
    ['congặp', 'con gặp'],
    ['mụchãy', 'mục hãy'],
    ['đượchoa', 'được hoa'],
    ['thiệnhơn', 'thiện hơn'],
    ['tinở', 'tin ở'],
    ['bịđe', 'bị đe'],
    ['sốnghằng', 'sống hằng'],
    ['tìmý', 'tìm ý'],
    ['khônghẳn', 'không hẳn'],
    ['Thầnhơn', 'Thần hơn'],
    ['đượcở', 'được ở'],
    ['cácơn', 'các ơn'],
    ['Phàmai', 'Phàm ai'],
    ['trọnhảo', 'trọn hảo'],
    ['đứcấy', 'đức ấy'],
    ['nănghơn', 'năng hơn'],
    ['mộtít', 'một ít'],
    ['thươnghọ', 'thương họ'],
    ['đặthy', 'đặt hy'],
    ['bằnghy', 'bằng hy'],
    ['đếnánh', 'đến ánh'],
    ['sànghy', 'sàng hy'],
    ['vốngiàu', 'vốn giàu'],
    ['hùnghồn', 'hùng hồn'],
    ['lìanhau', 'lìa nhau'],
    ['muốnai', 'muốn ai'],
    ['cuộchành', 'cuộc hành'],
    ['dụchoàn', 'dục hoàn'],
    ['nênhãy', 'nên hãy'],
    ['Nhưnghãy', 'Nhưng hãy'],
    ['thânyêu', 'thân yêu'],
    ['mếnanh', 'mến anh'],
    ['xứnghợp', 'xứng hợp'],
    ['cơngian', 'cơn gian'],
    ['cáchành', 'các hành'],
    ['chỉđể', 'chỉ để'],
    ['ấpủ', 'ấp ủ'],
    ['Cácông', 'Các ông'],
    ['chỉđược', 'chỉ được'],
    ['nhãnhiệu', 'nhãn hiệu'],
    ['phậnấy', 'phận ấy'],
    ['cơnghiệp', 'cơ nghiệp'],
    ['tinhằng', 'tin hằng'],
    ['đúnghơn', 'đúng hơn'],
    ['nhiệmấy', 'nhiệm ấy'],
    ['cũnghư', 'cũng hư'],
    ['conhay', 'con hay'],
    ['hấphối', 'hấp hối'],
    ['thíchứng', 'thích ứng'],
    ['thấphèn', 'thấp hèn'],
    ['sốnghoà', 'sống hoà'],
    ['mộthành', 'một hành'],
    ['conhiệp', 'con hiệp'],
    ['chậthẹp', 'chật hẹp'],
    ['nêngiàu', 'nên giàu'],
    ['chiếcáo', 'chiếc áo'],
    ['sốnghôn', 'sống hôn'],
    ['mắtanh', 'mắt anh'],
    ['khônghay', 'không hay'],
    ['conhiểu', 'con hiểu'],
    ['Đấnghằng', 'Đấng hằng'],
    ['giúpanh', 'giúp anh'],
    ['vậthữu', 'vật hữu'],
    ['thựchi', 'thực hiện'], // Assume typo for thực hiện? Or thực thi? Context needed. 'thựchi' -> 'thực thi' more likely if 'hi' is truncated. But 'thực hiện' is common. Wait 'thựchiện' was fixed. Maybe 'thực hi' remains? I'll replace with 'thực hiện'.
    ['toànhiến', 'toàn hiến'],
    ['congiúp', 'con giúp'],
    ['Giảnhư', 'Giả như'],
    ['đừnghổ', 'đừng hổ'],
    ['angiấc', 'an giấc'],
    ['conhạnh', 'con hạnh'],
    ['bằnghành', 'bằng hành'],
    ['Thựchiện', 'Thực hiện'],
    ['hoảnghốt', 'hoảng hốt'],
    ['đượchầu', 'được hầu'],
    ['vọnghồng', 'vọng hồng'],
    ['mấthết', 'mất hết'],
    ['tổnghợp', 'tổng hợp'],
    ['Ađam', 'Ađam'], // Name
    ['Têrêxa', 'Têrêxa'],
    ['Đavít', 'Đavít'],
    ['Vianney', 'Vianney'],
    ['Clara', 'Clara'],
    ['Phanxic', 'Phanxicô'], // Typo name?
    ['Samari', 'Samari'],
    ['Gôrétti', 'Gôrétti'],
    ['Xaviê', 'Xaviê'],
    ['Cana', 'Cana'],
    ['Vaticanô', 'Vaticanô'],
];

let count = 0;
for (const [pattern, replacement] of specificFixes) {
    if (content.includes(pattern)) {
        content = content.split(pattern).join(replacement);
        count++;
    }
}

console.log(`Applied ${count} types of specific sticky word fixes.`);

fs.writeFileSync(corpusPath, content, 'utf8');
